### ISSUE TITLE
how to install and use compiler

### ISSUE THREAD

**Issue by mlibre** [ndt93/mycoolc#1]
hello.
how can install and use your compiler.
and how to compile a .cl (cool file) with your program.
thanks for your time.

**Comment by ndt93** [comment]
Hi m-gh,

I haven't had time to complete the code generation phase of this compiler yet but it should be working well until the parser phase (in case you want to complete the compiler yourself).

You can compile the compiler up until the parser on a linux system with GNU build tools chain, e.g. you can execute `make parser` to generate the parser. Then the parser can be used like this `parser hello.cl` which will output an abstract syntax tree.

**Comment by mlibre** [comment]
ok . thanks
